# Generated by Django 5.0.2 on 2025-05-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='question_order_ids',
            field=models.JSONField(default=list),
        ),
    ]
