# Generated by Django 5.0.2 on 2025-05-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizattempt_question_order_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.CharField(blank=True, help_text='Enter a path or URL for the category image.', max_length=255),
        ),
    ]
